"""Provider-facing ports used by connector application services."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any, Protocol


SHAREPOINT_SOURCE = "sharepoint"
JIRA_SOURCE = "jira"


class SharePointProvider(Protocol):
    async def connect(self) -> Any: ...
    async def list_folder(self, folder_id: str | None = None) -> list[dict]: ...
    async def search(self, query: str, max_results: int = 20) -> list[Any]: ...
    async def search_in_folders(
        self, query: str, folder_urls: list[str], max_results: int = 20
    ) -> list[Any]: ...
    async def fetch(self, item_id: str) -> str: ...


class JiraProvider(Protocol):
    async def connect(self) -> Any: ...
    async def search(self, query: str) -> list[Any]: ...
    async def fetch(self, item_id: str) -> str: ...
    async def create_issue(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update_issue(self, *args: Any, **kwargs: Any) -> Any: ...
    async def add_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    async def transition_issue(self, *args: Any, **kwargs: Any) -> str: ...


class CalendarProvider(Protocol):
    async def list_calendar_events(self, **kwargs: Any) -> list[dict]: ...
    async def create_calendar_meeting(self, **kwargs: Any) -> dict: ...
    async def get_calendar_event(self, event_id: str) -> dict: ...


SharePointProviderFactory = Callable[[str], SharePointProvider]
JiraProviderFactory = Callable[..., JiraProvider]
CalendarProviderFactory = Callable[[str], CalendarProvider]
TokenInspector = Callable[[str], tuple[dict[str, Any], tuple[str, ...]]]
TokenValidator = Callable[[str], Awaitable[None]]

