"""Skill-discovery tools for sub-agents.

Discovery tools (always present) + typed tools for the skills the
orchestrator explicitly dispatched:

- ``list_skills`` — catalog (name / description / category / status) for
  discovery. Skills flagged as kind=skill AntiPatterns in this session
  are filtered out.
- ``load_skill`` — the full SKILL.md body. Strategy skills carry
  methodology text the sub-agent reads and applies; access skills
  carry usage notes (the actual call surface is the typed ``skill_*``
  tools, not ``load_skill``).
- ``skill_<name>`` — one typed tool per access skill the orchestrator
  named in ``skills=[...]`` for this dispatch (``render_skill_sets``).
  Skills that weren't dispatched stay discoverable via ``list_skills`` /
  ``load_skill`` but are not injected — no whole-library flood. Gated by
  ``enable_skills`` and the shared SKILL_ONLY/SKILL_EXCLUDE/blacklist;
  args are Pydantic-validated before the executor runs.

All access skills are ``agent_called`` (the url_routed dispatcher path
was removed) and are generated by the LLM-driven access-skill baker
(``ai.skills.evolution``).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from langchain_core.tools import tool


def _registry():
    from ai.research.agents.runtime import _skill_registry_var
    return _skill_registry_var.get()


# Only hide a skill when it's failed repeatedly — a single extraction
# miss could be a transient network / judge hiccup. Plan §6.4 bans "已
# 被证实无效"; one observation doesn't证实.
SKILL_BAN_MIN_OBSERVATIONS = 2


_VALIDATION_ERROR_MARKERS = (
    "missing required parameter",
    "required parameter",
    "missing required",
    "unknown function",
    "invalid function",
    "unsupported function",
    "must be one of",
)


def _is_validation_error(result: dict) -> bool:
    """True when the executor rejected the *call* (bad/missing args / unknown
    function) rather than failing to fetch data. Such errors mean the skill
    never ran — they're a caller bug, not evidence the source is dead, so they
    must not count toward the session-global skill ban.

    Recognises both an explicit ``error_type == "validation"`` (the canonical
    contract) and, for older skills that don't set it, a validation-shaped
    error string.
    """
    if str(result.get("error_type", "")).strip().lower() == "validation":
        return True
    err = result.get("error")
    if not err:
        return False
    err_l = str(err).lower()
    return any(m in err_l for m in _VALIDATION_ERROR_MARKERS)


def _banned_skills_from_state() -> set[str]:
    """Return skill names flagged as anti-patterns in the current session.

    Plan §6.4 with a guard: only skills with ``observed_count >=
    SKILL_BAN_MIN_OBSERVATIONS`` are hidden. A first-time failure still
    records the AntiPattern (for prompt-level "warn" surface) but
    doesn't yet remove the skill from discovery.
    """
    from ai.research.tools.search_state import _workspace_var
    ws = _workspace_var.get()
    if ws is None:
        return set()
    try:
        state = ws.load_state()
    except Exception:
        return set()
    banned: set[str] = set()
    for p in getattr(state.strategy_log, "patterns", []) or []:
        kind = getattr(p.kind, "value", str(p.kind))
        if (kind == "skill" and p.signature
                and p.observed_count >= SKILL_BAN_MIN_OBSERVATIONS):
            banned.add(p.signature)
    return banned


@tool
async def list_skills(category: str = "", status: str = "") -> str:
    """List available skills; returns JSON ``{skills:[{name, description, category, status, has_executor, trigger}], count, banned}``. Skills banned this session as kind=skill AntiPatterns are filtered out.

    Args:
        category (str): ``"strategy"`` | ``"access"`` | ``"orchestrator"`` — empty = all.
        status (str): ``"active"`` | ``"trial"`` | ``"seed"`` | ... — empty = all.
    """
    from searchos.config.settings import settings
    if not settings.enable_skills:
        return json.dumps({"skills": [], "count": 0, "note": "skill system disabled"})
    reg = _registry()
    if reg is None:
        return json.dumps({"skills": [], "count": 0, "error": "skill registry not bound"})
    banned = _banned_skills_from_state()
    out = []
    banned_hits = 0
    for s in reg.list_all():
        if s.meta.name in banned:
            banned_hits += 1
            continue
        if category and s.meta.category.value != category:
            continue
        if status and s.meta.status.value != status:
            continue
        out.append({
            "name": s.meta.name,
            "description": s.meta.description or s.meta.trigger or "",
            "category": s.meta.category.value,
            "status": s.meta.status.value,
            "has_executor": s.meta.has_executor,
            "trigger": s.meta.trigger,
        })
    return json.dumps(
        {"skills": out, "count": len(out), "banned": banned_hits},
        ensure_ascii=False,
    )


@tool
async def load_anti_patterns(skill_name: str, context: str = "") -> str:
    """Return full anti-pattern entries (踩坑 / 原因 / 改用) for a skill — call when a failure-mode summary in the prompt looks relevant.

    Args:
        skill_name (str): name of a skill from ``list_skills``.
        context (str): optional — short description of what you're about to try (or what just failed); when set, entries are reordered by relevance.
    """
    reg = _registry()
    if reg is None:
        return json.dumps({"error": "skill registry not bound"})
    s = reg.get(skill_name)
    if s is None:
        return json.dumps({"error": f"skill {skill_name!r} not found"})

    details = list(getattr(s, "anti_patterns_details", []) or [])
    if not details:
        return json.dumps({
            "skill": skill_name,
            "entries": [],
            "count": 0,
            "note": "no anti-patterns recorded for this skill",
        }, ensure_ascii=False)

    if context.strip():
        from ai.skills.core.anti_patterns import (
            AntiPatternEntry,
            rank_by_context,
        )
        entries_typed = [
            AntiPatternEntry(
                name=d.get("name", ""),
                summary=d.get("summary", ""),
                what_failed=d.get("what_failed", ""),
                why=d.get("why", ""),
                instead=d.get("instead", ""),
                observed=int(d.get("observed", 1) or 1),
                last_seen=d.get("last_seen", ""),
                source=d.get("source", ""),
            )
            for d in details
        ]
        ranked = rank_by_context(entries_typed, context)
        details = [
            {
                "name": e.name,
                "summary": e.summary,
                "what_failed": e.what_failed,
                "why": e.why,
                "instead": e.instead,
                "observed": e.observed,
                "last_seen": e.last_seen,
                "source": e.source,
            }
            for e in ranked
        ]

    return json.dumps(
        {"skill": skill_name, "entries": details, "count": len(details)},
        ensure_ascii=False, indent=2,
    )


@tool
async def load_skill(skill_name: str) -> str:
    """Return the full SKILL.md body. Strategy skills = methodology to fold into your next tool calls; access skills = usage notes (then call ``skill_<name>`` to execute).

    Args:
        skill_name (str): name of a skill from ``list_skills``.
    """
    reg = _registry()
    if reg is None:
        return json.dumps({"error": "skill registry not bound"})
    s = reg.get(skill_name)
    if s is None:
        return json.dumps({"error": f"skill {skill_name!r} not found"})
    return json.dumps(
        {
            "name": s.meta.name,
            "category": s.meta.category.value,
            "status": s.meta.status.value,
            "has_executor": s.meta.has_executor,
            "description": s.meta.description,
            "body": s.body,
        },
        ensure_ascii=False,
    )


def get_skill_tools(skill_names: list[str] | None = None) -> list:
    """Return the skill surface for one sub-agent dispatch.

    Always included: ``list_skills`` / ``load_skill`` / ``load_anti_patterns``
    (discovery — how an agent finds and reads any skill on demand).

    Appended: one typed ``skill_<name>`` tool per access skill the
    orchestrator **explicitly dispatched** in ``skills=[...]``
    (``skill_names``). Skills that weren't dispatched are NOT injected —
    the agent discovers them via ``list_skills`` and reads them via
    ``load_skill`` instead of every skill flooding the prompt. With no
    ``skill_names`` (e.g. the static agent-catalog) only the discovery
    tools are returned.
    """
    base = [list_skills, load_skill, load_anti_patterns]
    try:
        typed = render_skill_sets(skill_names or [])
    except Exception as e:  # noqa: BLE001
        # Never let a bad manifest break sub-agent startup.
        import logging
        logging.getLogger(__name__).warning(
            "failed to build typed skill tools: %s", e,
        )
        typed = []
    return [*base, *typed]


# ---------------------------------------------------------------------------
# Typed-tool rendering for dispatched agent-called skills
# ---------------------------------------------------------------------------

def invalidate_typed_tools_cache() -> None:
    """No-op kept for call-site compatibility.

    Typed tools are now rendered per dispatch from the orchestrator's
    ``skills=[...]`` list (``render_skill_sets``), not cached by library
    path, so a freshly-baked skill is picked up on its next dispatch with
    nothing to invalidate.
    """
    return None


def render_skill_sets(skill_names: list[str]) -> list:
    """Build typed ``skill_<name>`` tools for the dispatched access skills.

    Only skills the orchestrator named in ``skills=[...]`` become tools;
    everything else stays discoverable via ``list_skills`` / ``load_skill``
    but is not injected. For each name we resolve its manifest through the
    bound ``SkillRegistry`` and keep it only if it declares
    ``invocation: agent_called`` + a ``params_schema``.

    Gated by ``enable_skills`` and filtered by the same names as every
    other skill — ``SEARCHOS_SKILL_ONLY`` / ``SEARCHOS_SKILL_EXCLUDE``
    plus the hard ``SKILL_BLACKLIST``.
    """
    from searchos.config.settings import settings
    if not settings.enable_skills or not skill_names:
        return []

    reg = _registry()
    if reg is None:
        return []

    import yaml

    from ai.skills.catalog.registry import (
        SKILL_BLACKLIST,
        _env_excluded,
        _env_only,
    )
    only = _env_only()                          # None = no whitelist
    excluded = _env_excluded() | set(SKILL_BLACKLIST)

    tools: list = []
    seen: set[str] = set()
    for name in skill_names:
        name = str(name).strip()
        if not name or name in seen:
            continue
        seen.add(name)
        if only is not None and name not in only:
            continue
        if name in excluded:
            continue

        skill = reg.get(name)
        if skill is None or not skill.file_path:
            continue
        manifest_path = Path(skill.file_path).parent / "manifest.yaml"
        if not manifest_path.exists():
            continue
        try:
            with open(manifest_path, encoding="utf-8") as f:
                data = yaml.safe_load(f) or {}
        except Exception:
            continue
        params_schema = data.get("params_schema") if isinstance(data, dict) else None
        if not isinstance(params_schema, dict) or not params_schema:
            continue

        try:
            tool_obj = _make_typed_tool(
                skill_name=name,
                skill_dir=manifest_path.parent,
                description=str(data.get("description") or "").strip(),
                params_schema=params_schema,
            )
        except Exception as e:  # noqa: BLE001
            import logging
            logging.getLogger(__name__).warning(
                "skipping typed tool for %s: %s", name, e,
            )
            continue
        tools.append(tool_obj)

    return tools


_YAML_TYPE_TO_PY = {
    "string": str,
    "str": str,
    "integer": int,
    "int": int,
    "number": float,
    "float": float,
    "boolean": bool,
    "bool": bool,
    "array": list,
    "list": list,
    "object": dict,
    "dict": dict,
}


def _make_typed_tool(
    *,
    skill_name: str,
    skill_dir: Path,
    description: str,
    params_schema: dict,
):
    """Build one LangChain StructuredTool for a single agent-called skill.

    Steps:
    1. Construct a Pydantic model from ``params_schema`` — field types,
       defaults, and requiredness match the manifest.
    2. Wrap a coroutine that delegates to ``run_executor`` with the
       validated params + the current session's browser / query.
    3. Register the coroutine as a StructuredTool named
       ``skill_<skill_name>`` — this is what the sub-agent calls.
    """
    from langchain_core.tools import StructuredTool
    from pydantic import Field, create_model

    # Build Pydantic model fields
    fields: dict[str, tuple[Any, Any]] = {}
    for param_name, raw_spec in params_schema.items():
        if not isinstance(raw_spec, dict):
            continue
        yaml_type = str(raw_spec.get("type", "string")).strip().lower()
        py_type = _YAML_TYPE_TO_PY.get(yaml_type, str)
        required = bool(raw_spec.get("required", False))
        desc = str(raw_spec.get("description", "")).strip()

        if required:
            fields[param_name] = (py_type, Field(..., description=desc))
        else:
            default = raw_spec.get("default")
            # Distinguish "no default declared" (None) from "default is None":
            # since YAML can't express that subtlety, treat missing `default`
            # as "use the type's zero value" for consistency.
            if default is None:
                default = {str: "", int: 0, float: 0.0, bool: False, list: [], dict: {}}.get(py_type)
            fields[param_name] = (py_type, Field(default=default, description=desc))

    if not fields:
        raise ValueError(f"empty params_schema for {skill_name}")

    ParamsModel = create_model(f"{skill_name}_params", **fields)  # type: ignore[call-overload]

    async def _run(**kwargs: Any) -> str:
        """Executes the underlying skill and returns JSON-serialised result."""
        # Ban check — mirror list_skills' filtering so skills flagged as
        # AntiPatterns this session can't be called via typed tool either.
        banned = _banned_skills_from_state()
        if skill_name in banned:
            return json.dumps({
                "error": f"skill {skill_name!r} has been banned this session "
                         "(repeated failures); try another approach."
            })

        from ai.research.agents.orchestrator.lifecycle import _ctx, _record_skill_failure
        from ai.skills.runtime.executor_runtime import run_executor

        query = ""
        if _ctx.workspace is not None:
            try:
                query = _ctx.workspace.load_state().intent or ""
            except Exception:
                pass

        result = await run_executor(
            skill_dir,
            dict(kwargs),
            query=query,
        )

        # Failure signal = the executor's own verdict. Evidence is extracted
        # asynchronously by the middleware (batched flush), so an evidence-count
        # delta can't be measured synchronously here — using it would record a
        # false failure on every call and ban working skills.
        #
        # Input-validation errors (bad/missing args) mean the executor never
        # ran — the skill never touched the network. Counting them toward the
        # session ban lets a malformed-call loop poison a working source for
        # every agent (the www_universityrankings_ch regression). Only genuine
        # run-time failures (network / no-evidence) count.
        if isinstance(result, dict) and (
            result.get("error") or result.get("success") is False
        ) and not _is_validation_error(result):
            _record_skill_failure(skill_name, dict(kwargs))

        # No indent: pretty-printing a 1000-row result wastes ~30% on
        # whitespace in the agent's context. Oversized payloads are further
        # compacted by the extraction middleware before reaching the agent.
        return json.dumps(result, ensure_ascii=False)

    tool_description = description or f"Agent-called skill: {skill_name}"
    # Document the shape that ends up in the sub-agent's tool list.
    params_doc = "\n".join(
        f"- {pname}: {params_schema[pname].get('description', '').strip()}"
        for pname in params_schema
        if isinstance(params_schema[pname], dict)
    )
    if params_doc:
        tool_description = f"{tool_description}\n\nParameters:\n{params_doc}"

    return StructuredTool.from_function(
        coroutine=_run,
        name=f"skill_{skill_name}",
        description=tool_description,
        args_schema=ParamsModel,
    )
